### PR TITLE
Fixed a problem with some students seeing an error page when trying to review an ended run

### LINKED ISSUE #1930: Error page when workgroup reviews ended run
### Description

As a teacher
1. Create a run

As a student
2. Register to the run and create a workgroup with 2 or more students
3. Launch the run

As the teacher
4. End the run

As the student
5. Go to the student home page
6. Review the run. The student will see a Whitelabel Error Page with the error below

```
There was an unexpected error (type=Internal Server Error, status=500).
Neither BindingResult nor plain target object for bean name 'teamSignInForm' available as request attribute
java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name 'teamSignInForm' available as request attribute
```

We may be able to fix the problem by changing student-run-list-item.component.ts. We can change the skipTeamSign() function so that it does something like
```
window.location.href = `/student/run/${this.run.id}`;
```

### LINKED ISSUE #1931: If a run has students per team set to 1, students that launch the run will not have attendance recorded
### Description

The student run statistics will also not be updated.

As the teacher
1. Create a run with students per team set to "only 1 student"

As a student
2. Register to the run
3. Launch the run

In StudentAPIController.java the performLaunchRun() function is called if students per team is set to 3. This function will not be called if students per team is set to 1.

### PR DESCRIPTION
**Pull request by geoffreykwan**
**Test error page issue**
As a teacher
1. Create a run with students per team set to 3 and make it active

As a student
2. Add the run
3. Launch the run

As the teacher
4. End the run by setting the end time to a time in the past

As a student
5. Go to the student home page.
6. Review the run. Make sure there is no error page.

**Test student attendance issue**
As a teacher
1. Create a run with students per team set to 1 and make it active

As a student
2. Add the run
3. Launch the run. Make sure the student attendance is recorded in the database in the student_attendance table.

Closes #1930
Closes #1931

### CODE REVIEW

File: src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts [hunk 1]
```diff
@@ -210,8 +210,7 @@ export class TeamSignInDialogComponent implements OnInit {
   }
 
   launchRun() {
-    const presentUserIds = [];
-    presentUserIds.push(this.user.id);
+    const presentUserIds = [this.user.id];
     const absentUserIds = [];
     for (let member of this.teamMembers) {
```
Comment (hirokiterashima) [inline src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts]:
```suggestion
    for (const member of this.teamMembers) {
```

File: src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.spec.ts [hunk 2]
```diff
@@ -9,6 +9,8 @@ import { Project } from "../../domain/project";
 import { User } from "../../domain/user";
 import { NO_ERRORS_SCHEMA } from "@angular/core";
 import { MatDialog } from "@angular/material";
+import {StudentService} from "../student.service";
```
Comment (hirokiterashima) [inline src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.spec.ts]: Put spaces around import for lines 12 and 13

File: src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.ts [hunk 3]
```diff
@@ -5,6 +5,9 @@ import { SafeStyle } from '@angular/platform-browser';
 import { ConfigService } from "../../services/config.service";
 import { MatDialog } from "@angular/material/dialog";
 import { TeamSignInDialogComponent } from "../team-sign-in-dialog/team-sign-in-dialog.component";
+import {Student} from "../../domain/student";
```
Comment (hirokiterashima) [inline src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.ts]: Put spaces around import for lines 8-10
