### PR TITLE
fixed issue student adding teacher as teammate

### LINKED ISSUE #1702: Team Sign In: should not be able to add a teacher who didn't create the run
### Description

A teacher should not be able to belong in a workgroup with students. Right now the teacher of the run can not because they automatically get added into a workgroup when they create the run. A teacher who did not create the run can be added as a teammate.

### Steps to Reproduce

1. Try to sign in to a run with a teacher who did not create the run

**Expected behavior:**
An error message should be displayed with the message "A teacher cannot be added as a team member"

**Actual behavior:**
The teacher is added to the team.

### PR DESCRIPTION
**Pull request by vkorir**
1. Log in as a student
2. Click on the Launch button
3. Try adding a teacher as a teammate

- verify that a student shouldn't be able to add a teacher as a teammate
- verify that a warning is displayed when a student attempts to add a teacher as teammate

closes #1702

### CODE REVIEW

File: src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts [hunk 1]
```diff
@@ -79,12 +79,15 @@ export class TeamSignInDialogComponent implements OnInit {
...
               .subscribe((canBeAddedToWorkgroupResponse) => {
-          if (canBeAddedToWorkgroupResponse.status) {
+          if (canBeAddedToWorkgroupResponse.status && !canBeAddedToWorkgroupResponse.isTeacher) {
             teamMember.id = response.userId;
             teamMember.userName = response.userName;
             teamMember.firstName = response.firstName;
             teamMember.lastName = response.lastName;
             this.markAsSignedIn(teamMember);
+          } else if (canBeAddedToWorkgroupResponse.isTeacher) {
+            alert("A teacher cannot be added as a team member");
```
Comment (geoffreykwan) [inline src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts]: Can you add i18n to line 89? Do it like line 134.

File: src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts [hunk 2]
```diff
@@ -119,12 +122,14 @@ export class TeamSignInDialogComponent implements OnInit {
...
                 .subscribe((canBeAddedToWorkgroupResponse) => {
-                  if (canBeAddedToWorkgroupResponse.status) {
+                  if (canBeAddedToWorkgroupResponse.status && !canBeAddedToWorkgroupResponse.isTeacher) {
                     teamMember.id = response.userId;
                     teamMember.userName = response.userName;
                     teamMember.firstName = response.firstName;
                     teamMember.lastName = response.lastName;
                     this.markAsSignedIn(teamMember);
+                  } else if (canBeAddedToWorkgroupResponse.isTeacher) {
+                    alert("A teacher cannot be added as a team member");
```
Comment (geoffreykwan) [inline src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.ts]: Can you add i18n to line 132? Do it like line 134.
