### PR TITLE
Share run: add/revoke shared teacher does not update view automatically

### LINKED ISSUE #2045: Share run: add/revoke shared teacher does not update view automatically
### Description

Adding or revoking a shared teacher from a run does not automatically update the displayed list of shared teachers for that run.

### Steps to Reproduce

1. Add shared teacher to run
2. Remove shared teacher from run

**Expected behavior:**

1. The shared teacher should appear in the shared teachers list dialog
2. The shared teacher should be removed from the shared teachers list dialog

**Actual behavior:**

1. The shared teacher does not appear in the shared teachers list dialog
2. The shared teacher is not removed from the shared teachers list dialog

### PR DESCRIPTION
**Pull request by geoffreykwan**
1. Create a run
1. Share the run with another teacher. The shared teacher should immediately show up as a shared teacher.
1. Revoke the shared teacher. The shared teacher should immediately be removed from the shared teachers.
1. Transfer the run to another teacher. The share run dialog should immediately update to show the new owner and also show the previous owner as a shared owner.

Closes #2045

### CODE REVIEW

File: src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts [hunk 1]
```diff
@@ -91,16 +91,16 @@ export class ShareRunDialogComponent extends ShareItemDialogComponent {
     if (isAddingPermission) {
       this.teacherService.addSharedOwnerRunPermission(this.runId, sharedOwnerId, permissionId)
           .subscribe((response: any) => {
-            if (response.status == "success") {
-              this.addRunPermissionToSharedOwner(sharedOwnerId, permissionId);
-            }
+        if (response.status == "success") {
```
Comment (hirokiterashima) [inline src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts]:
```suggestion
        if (response.status === 'success') {
```

File: src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts [hunk 2]
```diff
@@ -91,16 +91,16 @@ export class ShareRunDialogComponent extends ShareItemDialogComponent {
...
+        }
       });
     } else {
       this.teacherService.removeSharedOwnerRunPermission(this.runId, sharedOwnerId, permissionId)
-        .subscribe((response: any) => {
-          if (response.status == "success") {
-            this.removeRunPermissionFromSharedOwner(sharedOwnerId, permissionId);
-          }
+          .subscribe((response: any) => {
+        if (response.status == "success") {
```
Comment (hirokiterashima) [inline src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts]:
```suggestion
        if (response.status === 'success') {
```
